### ISSUE TITLE
AssumeRule broken, mai unusable

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/mai#6]
``` shell
$ mai
Authenticating against https://xxxxxxxxxx.. OK
Assuming role AWS Account XXXXXXXXXXX (xxxxxxxxxx): XXXXXXXXX.. EXCEPTION OCCURRED: 'Session' object has no attribute 'get_service'
Traceback (most recent call last):
  File "/usr/local/bin/mai", line 9, in <module>
    load_entry_point('stups-mai==0.12', 'console_scripts', 'mai')()
  File "/usr/local/lib/python3.4/dist-packages/mai/cli.py", line 248, in main
    cli()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 971, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mai/cli.py", line 49, in cli
    login_with_profile(profile, data.get(profile))
  File "/usr/local/lib/python3.4/dist-packages/mai/cli.py", line 187, in login_with_profile
    key_id, secret, session_token = assume_role(saml_xml, role[0], role[1])
  File "/usr/local/lib/python3.4/dist-packages/aws_saml_login/saml.py", line 164, in assume_role
    sts = session.get_service('sts')
AttributeError: 'Session' object has no attribute 'get_service'
```

My feeling is that its connected to pip3 update, after update of pip, it doesn't work anymore:

```
$ pip3 --version
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
```

Maybe connected with #3 ?

**Comment by sarnowski** [comment]
Actually, it is exactly the method, that the deprecation warning talked about in #3 .

**Comment by sarnowski** [comment]
Workaround until fix:

``` shell
$ sudo pip3 install botocore==0.91.0
```

background: botocore 1.0.0 released which seemed to had a big cleanup where they removed all deprecated stuff

**Comment by hjacobs** [comment]
Will fix...
